In [111]:
import pickle
import pandas as pd
import datetime
import os

from dotenv import load_dotenv

from langchain_core.documents import Document
from langchain_core.vectorstores import InMemoryVectorStore
from langchain_ollama import OllamaEmbeddings
from langchain_core.prompts import ChatPromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.chains import RetrievalQA
from langchain.agents import AgentExecutor, create_tool_calling_agent, tool

from ragas import evaluate, RunConfig
from ragas import EvaluationDataset
from ragas.dataset_schema import EvaluationResult
from ragas.llms import LangchainLLMWrapper
from ragas.metrics import LLMContextRecall, Faithfulness, FactualCorrectness

In [112]:
load_dotenv()

True

In [43]:
train_df = pd.read_json("train_short.json")

# traindf where wellformedanswers is not empty
train_df.drop(columns=["query_id", "query_type", "wellFormedAnswers"], inplace=True)

# for answer in column answers apply lambda function to get the first element
train_df["answers"] = train_df["answers"].apply(lambda x: x[0] if len(x) > 0 else None)

# split passages into twenty columns (passage_0_text, passage_0_is_selected, passage_1_text, passage_1_is_selected, ...)
for i in range(10):
    passage_text = train_df["passages"].apply(lambda x: x[i]["passage_text"])
    passage_is_selected = train_df["passages"].apply(lambda x: x[i]["is_selected"])
    train_df[f"passage_{i}_selected"] = passage_is_selected
    train_df[f"passage_{i}_text"] = passage_text

# drop columns passage
train_df.drop(columns=["passages"], inplace=True)

# train_df = train_df.iloc[:10]
train_df = train_df[:200]
train_df

,answers,query,passage_0_selected,passage_0_text,passage_1_selected,passage_1_text,passage_2_selected,passage_2_text,passage_3_selected,passage_3_text,...,passage_5_selected,passage_5_text,passage_6_selected,passage_6_text,passage_7_selected,passage_7_text,passage_8_selected,passage_8_text,passage_9_selected,passage_9_text
0,The immediate impact of the success of the man...,)what was the immediate impact of the success ...,1,The presence of communication amid scientific ...,0,The Manhattan Project and its atomic bomb help...,0,Essay on The Manhattan Project - The Manhattan...,0,The Manhattan Project was the name for a proje...,...,0,The Manhattan Project. This once classified ph...,0,Nor will it attempt to substitute for the extr...,0,Manhattan Project. The Manhattan Project was a...,0,"In June 1942, the United States Army Corps of ...",0,One of the main reasons Hanford was selected a...
1,Restorative justice that fosters dialogue betw...,_________ justice is designed to repair the ha...,0,"group discussions, community boards or panels ...",0,punishment designed to repair the damage done ...,0,Tutorial: Introduction to Restorative Justice....,0,"Organize volunteer community panels, boards, o...",...,0,Each of these types of communities—the geograp...,1,The approach is based on a theory of justice t...,0,Inherent in many people’s understanding of the...,0,"Criminal justice, however, is not usually conc...",0,The circle includes a wide range of participan...
2,The customer care number of Amex India is 1800...,amex india customer care number,0,American Express is the world's premier servic...,0,Customer Service Main Page: Get Information: U...,1,Amex Card India Customer Care Phone Number Pho...,0,Air India American Express Gold Card Customer ...,...,0,"Update Address, Payee Name, Bank Account and C...",0,Please mention the first 11 digits of your Ame...,0,"The postal and official address, email address...",0,Corporate Cardmembers can contact the 24 hour ...,0,Through which any customers can easily contact...
3,"Ramen is a quick-cooking noodles, typically se...",definition of ramen,0,"Ramen is of Chinese origin, however it is uncl...",0,"ramen definition, meaning, what is ramen: a Ja...",0,Definition of ramen written for English Langua...,0,Sapporo ramen comes from Japan's northernmost ...,...,0,Wiktionary (0.00 / 0 votes) Rate this definiti...,0,Related dishes. 1 Nagasaki champon. The noodl...,0,[sometimes with sing. v.] Japanese noodles of ...,0,"‘The noodles, most of which we left behind bec...",0,"On the ground floor level, there is a souvenir..."
4,Rachel Carson died because of cancer.,why did rachel carson die,0,A Fish and Wildlife Service National Wildlife ...,0,Though much of their correspondence was destro...,0,The impetus for Silent Spring was a letter wri...,0,How about the environmentalist and writer Rach...,...,0,"Rachel Carson was born on May 27, 1907, on a f...",0,Lived 1907 – 1964. Rachel Carson played a key ...,0,Rachel Carson had a large love for nature and ...,1,Heroes commit feats of courage involving risk ...,0,"To passers-by the mother would say, pointing, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,One of the most common reasons for an HP wirel...,why does a network printer go offline,0,If It Is A Shared Network Printer. If the prin...,0,Why did your HP Wi-Fi printer go offline? A: A...,0,A: One of the most common reasons for an HP wi...,0,2) Click on Devices and Printers in Large or S...,...,0,"However, if this option does not solve your pr...",1,Quick Answer. One of the most common reasons f...,0,The following settings need to be checked; 1) ...,0,Why is My Printer Offline? there could be seve...,0,Let’s Fix it. 1) Go to control panel. On Windo...
196,A person waives pip coverage because they beli...,why does a person waives pip coverage,0,"In such states PIP coverage is not mandated, g...",0,"Alternatively, if your health insurance doesn'...",0,Medical payments coverage and health insurance...,0,You cannot claim any pain and suffering and ha...,...,0,PIP pays the medical expenses for injuries sus...,0,Who it covers. 1 Person named on the policy. ...,0,Personal Injury Protection coverage does not o...,0,"PIP coverage can include medical expenses, los...",1,"Personal injury protection coverage, or PIP in..."
197,No Answer Present.,why does a reduction reaction always accompany...,0,There is no net change in charge in a redox re...,0,The first step toward a theory of chemical rea...,0,Oxidation-Reduction Reactions. Redox reactions...,0,"A redox, or reduction-oxidation reaction is on...",...,0,"If one atom or molecule is giving electrons, a...",0,Oxidation is the loss of electrons Reduction i...,0,"When natural gas burns, for example, an oxidat...",0,Because a reducing agent is always transformed...,0,Oxidation and reduction reactions involve an e...
198,No Answer Present.,why does a salamander have slimy skin,0,"However, we can guarantee that someone very ex...",0,Hellbenders have gone by other nicknames as we...,0,Habi­tat. The slimy sala­man­der is com­monly ...,0,Salamanders are amphibians that look like a cr...,...,0,Amphibians have gills when they are young or t...,0,That way they can help maintain moist and wet ...,0,If you found the salamander in the late spring...,0,Salamanders rarely have more than four toes on...,0,Those species of salamander that live undergro...
199,No Answer Present.,why does a sitting cup have potential energy,0,Potential energy. Potential energy is stored e...,0,When a car is moving it has kinetic energy. Wh...,0,Many people have correctly responded to your f...,0,Students explore the physics exploited by engi...,...,0,Whether the car is moving along the road or at...,0,Kinetic Energy is energy of motion. An object ...,0,"After this activity, students should be able t...",0,"Before the lesson, make sure students have a f...",0,New Method to Motivate Students to Reduce Ener...

,answers,query,passage_0_selected,passage_0_text,passage_1_selected,passage_1_text,passage_2_selected,passage_2_text,passage_3_selected,passage_3_text,...,passage_5_selected,passage_5_text,passage_6_selected,passage_6_text,passage_7_selected,passage_7_text,passage_8_selected,passage_8_text,passage_9_selected,passage_9_text
34,Britain and France declared war on Germany fol...,why did we declare war on germany?,0,"For example: 1 In 1905 and 1911, there were d...",0,The United States later declared war on German...,1,Why did Britain and France declare war on Germ...,0,"On 11 December 1941, four days after the Japan...",...,0,54 Answers. The United States entered the war ...,0,Why did the U.S. declare war on Germany during...,0,The President said a declaration of war would ...,0,We will not only defend ourselves to the utter...,0,"On 11 December 1941, four days after the Japan..."

In [44]:
sample_queries = list(train_df['query'])
expected_responses = list(train_df['answers'])

# create a list of every passage, also append the rowid stretched to 4 digits + passage_0_selected number
passages = []
for i, row in train_df.iterrows():
    for j in range(10):
        passage = row[f"passage_{j}_text"]
        passage_is_selected = row[f"passage_{j}_selected"]
        id = f"{int(i):04d}_{passage_is_selected}"
        passages.append((id, passage))

In [45]:
dataset_documents = [
    Document(
        page_content=one_passage,
        metadata={
            "id": one_id,
        }
    ) for one_id, one_passage in passages
]

In [46]:
embeddings = OllamaEmbeddings(model="mxbai-embed-large")
dataset_vector_store = InMemoryVectorStore(embeddings)

In [47]:
dataset_vector_store.add_documents(dataset_documents)

['9d0632ec-8d82-4c6f-b9c6-97cd205bde4c',
 '9de3d825-e817-444e-8771-78edf666d536',
 '831cdd09-50fe-4c2d-a991-b8a344f47f69',
 '9f9c1bc2-4247-472d-a73c-36581e7f25d4',
 'ab09098c-ab3d-441f-b0f1-777789672a47',
 'e09c47e6-de50-4d05-9ff8-31a48d67c0b0',
 '49889dbf-fd00-457e-b73a-537f812dfbaa',
 'c5d3b565-2c90-4e63-a59d-4b9cb3482418',
 '52c920f3-bada-4e0e-883a-c34a6337c655',
 '54653dce-dfd9-4759-8175-9a80644542f9',
 '41837272-2e76-4be9-a6f4-95a9d51c8f95',
 'bd37adac-598a-4632-981a-3f1c9ee78c85',
 '1fd8fae3-e8c2-41e5-9e05-d6655afb2597',
 'c289d7af-7ccd-441d-a2ad-ace883de416a',
 '179c503f-cb30-437e-bb54-321bd4348eee',
 '8de9a6ff-3159-4d58-bba7-f49bee59c0c4',
 '5b87c404-49aa-4896-8caf-37438cb5575c',
 '144b8eff-3900-4ed7-a4df-7af731991bcc',
 '944212c5-6994-4cdb-ac3d-393fed72a7f9',
 '66ce716c-8e21-478b-a105-3c5ca6a94bf6',
 '69fa4c64-1b3a-4ad0-86e8-e3c7e12a7423',
 '6f878a2f-06d4-4b04-af6e-f436e225e372',
 'f6ce248d-38d3-458a-b7e6-17e16057b9d7',
 'efd0fcaa-3fb5-4ffc-a2b0-7619d9fd4317',
 'db2fa254-9d82-4b5e-9209-65e06bf19a6b',
 '2013a05f-140a-4db1-abaf-5e1a78bb2b66',
 '6359ddf7-59ef-4786-867e-00937dd77b1f',
 'fa068974-5c86-4c98-8eba-c028d4328de2',
 '9bbb9e54-7d18-440a-997c-560506216878',
 'f3c713b7-7681-4131-898d-92ce2b9bd123',
 '5588ceb9-b7cd-49b8-ac95-7af585afdc27',
 '8d523202-8f0a-4dd2-ae9f-4c7ac1a99093',
 'd0a569f7-2f5e-4142-92b3-51208c6b5667',
 'feb58c35-024a-47a4-9d5e-b546d9a79363',
 '20d39f1c-6661-4901-8688-9e9391380700',
 '644c59f1-73d0-4231-a6ca-1d4cbdfe77b7',
 'df6251d5-04d6-40f4-a831-37aeace468ea',
 '235b9530-7882-4460-94f6-15789abff176',
 '2895acf8-a2dd-4d13-a0f1-cd51ad0e6f4d',
 '16c66f1b-1649-435a-b87b-55c4e58ebeba',
 '5aa9d209-2a8a-45f7-b015-37687b9d0975',
 '27f85b22-3bef-4cd4-8dc0-771c76c46f1b',
 '43db2780-7ad5-4ff6-9171-7d6164a915d8',
 'b52a54ba-a492-4b13-aa6e-c692b2a9201f',
 '2c943d0f-c694-4977-a09e-80209b129024',
 '7499ed31-a382-48e2-8d58-ffc6f47a4b70',
 '2c57f8ea-965b-4e99-842d-502d27a4ad81',
 'd726cc49-acb1-44e7-8821-10a6b913291f',
 'bbb6aafa-3f03-4078-a68a-83f3de06733c',
 'a6775ecf-ed1b-4006-934e-83bb5e4f3a14',
 '15b19ea3-4214-4f36-8be4-4dd30bcbaedc',
 '46c306f7-c22b-4304-99fd-408d312a7b84',
 '0be12dfc-a86d-4894-8454-aac32acf4067',
 'c9ad483c-d973-4397-b54f-f4d6669003aa',
 'b7ea8349-c211-443a-90e8-9de7dc1012e2',
 'c6922cc4-c6bb-48c7-af5a-a443bfa7dfb8',
 '99e7c4ea-a6e7-4af7-ba39-e32ccfa267a9',
 '914f9010-415f-413b-b9b9-bd4302a8a9db',
 '0a416502-45c6-4f35-ad00-cac7831e80d3',
 'd00495da-ffd0-4c1d-8a40-07b3f7433ce3',
 'efe981fb-1bff-458f-abc7-2db5ab882360',
 '12338188-607f-4ef2-8d49-5fdee5397cfc',
 'f7d0fc5d-e4e9-4fe9-b8c8-1c9579a2e32d',
 '59ba4601-a0b6-4454-b26b-26f247b174d0',
 '58a1af9e-d847-480d-837b-6e774f049c27',
 'a0621a49-f066-4347-a4bb-33dc1a34315e',
 '65c4b1d0-090e-42b4-ab60-f49b73d1183c',
 'f0c6e4a3-cced-446b-b10f-a96966825e69',
 '33cfa09c-4e96-416a-bcc7-e72ba119a0e8',
 '70fc40da-09a2-4bb8-942a-24bee91e9b4c',
 '5cfd1b2f-4416-48d1-bdad-56c3a3ab5d54',
 '75e07527-fdd1-4509-8f15-bc0ada671b18',
 '4d9f73c6-a5d6-4224-bae1-39cf780e25b0',
 '5b560a24-5121-439d-9372-58ad229d6195',
 'fc559758-32ee-4d81-b291-e3a974c262cc',
 '157f0091-d4a2-4ef7-992e-0fb96808e1b7',
 '67bb44a9-a27a-419c-8df1-7e51578fce06',
 '31b6e4c2-0677-4fde-a783-1c1da6a5067c',
 'b6f61d87-06b3-42b8-964c-7d01ee5c012f',
 '7a6cc434-a3f2-4668-9368-8b07f2f736b5',
 '4615322a-615e-4d62-ab04-3e80e78b11b5',
 'c92cb3be-166a-48dc-a625-fa269cc8a82c',
 '6451e68a-6df5-4665-884f-bec7ad9e7774',
 '7f56033e-c56b-4133-baad-33eb3c9638cb',
 '8478eadd-618d-4d53-b8ad-9fa1a7907791',
 '1e71ccbf-54a2-465b-be40-c804162a88c9',
 'e035307e-0a0a-435d-9b07-247753a65ca4',
 '55669af8-7fc7-45cd-a116-257d8608b89e',
 '29ab5811-b1ea-4973-8c07-000bdb921332',
 'c5397f64-b9c6-4a99-a99d-72cc282c0f37',
 '3bde698a-ba35-457d-8ff2-62aabf98f4dd',
 '9cd6e775-a190-4d8f-916e-192d73a2c7fd',
 '458789a7-5fd5-4d96-befd-756d0bb9b465',
 'a0eba4a9-c151-4666-b2b5-7e1311786f12',
 'd5b9659e-5d94-46ff-ae60-bca78e1a322d',
 'e293ec02-b890-4aad-a0fe-e2f910c619c1',
 'b8046726-0464-4794-b7ea-0554952c1abd',
 '1ca0cee8-a16a-4323-ac9d-04ebdcb583f4',
 '9658bc70-35ff-472e-a4d9-220f2c80e54a',
 '8f391bd2-f067-44e7-af8f-6a2edc0a5b46',
 'd1f5715a-3e25-4f37-825e-693820ad502d',
 '5e781cc7-8bcd-493b-9a1c-5826808041ff',
 'f53b3b4d-eb4b-49aa-81a7-c67faace32a6',
 '73813e1b-30ac-426e-8b48-6566c7de7510',
 '222d7acb-b02b-417f-aff8-d0093068fbe0',
 '79f5ae78-c9c1-44a9-b942-2fb573dd0dc6',
 '564cdea4-82b5-43ee-8efa-c33e3c83fe9e',
 '5988ed7c-9674-4994-a95b-93ded6b512ef',
 'fab06d35-305b-4ebf-ac52-4c8e6b184658',
 '80e4bd8e-0cc1-4bba-8d92-9b323c094af1',
 '48de32a1-e4a5-4c52-8bec-8b15299bb5a7',
 '3472602d-c447-46a2-8ebe-c3641909d2c0',
 '40df6b97-b0e3-4e66-807e-060a9922e6e4',
 'ac2c6c8f-f584-4b94-b6bf-ec3be4abaf44',
 '659fe7e6-e207-49b1-b0be-0d2308ec800f',
 'e599d9d6-8d32-45ad-91af-c804a481cd5b',
 '82e6bf7c-3f32-43ec-9918-16e1802c6dd4',
 '07aac013-1f84-4369-bbe9-c0523480144b',
 'fb504fc9-d2b8-4f61-a6ea-3876912f4df5',
 'b03109cf-909e-4ac0-b594-ab8caad4e9f6',
 '3f210047-5473-4e2a-99b4-453d4ef1cb8b',
 'b76e7143-570f-4992-8618-8d742b2b60fc',
 'b7223c3b-9ba5-44db-9e8a-04023abbd174',
 '8a1b4ef3-d381-4d3b-a7f0-649c41a5c815',
 'abccc5bd-8854-4dba-8f37-ebf3cab1a023',
 'f62fbbbb-ef47-4152-82f3-dcc6c0822bb2',
 'b8fc8a57-8e42-4374-a7b1-dbcf8709204d',
 '65159f81-d997-4b66-bb5f-ec67d512c65a',
 '4c325358-7022-4d30-a1fc-c28651db5b18',
 '38d5ee4d-e73f-4550-865c-294cfe9e1adb',
 '6ef2f32c-5f47-4c00-ad8d-1c869a70cd49',
 '695a31ea-baef-40d7-83fa-69e461aa1c2e',
 '1e1136f9-50f8-4c78-9c34-ef686fda4f6b',
 'd2fc1c49-c529-408c-b082-13de35f50af5',
 'b209474f-dba9-45c0-bec0-90b03ae72b3d',
 '2dc107f4-6ac5-45b5-83db-5f08da0647ef',
 '36ef6def-1e5b-4501-aeb8-6f8f4d3470b7',
 '9b8cdba6-ef54-459b-9c58-8755eed63461',
 '04072385-9bcf-41bf-8461-d1e39aee4dfd',
 'dcd0eb93-1de0-4838-90f4-cd6a13be0fe5',
 'e63dacc3-65ef-449c-b986-8de747ed9ce3',
 'af46a815-aa38-47a5-9c39-5e46f7403a96',
 '46772338-bedc-4f56-bb99-6ef003e441fa',
 'd39a28a2-3c51-486c-b32d-eb389e971b99',
 '87860902-7c7d-4203-b69e-4357ba79bbde',
 'e7343272-a100-47f9-93a0-da837908feca',
 'faf65c84-89bc-4847-9c9a-2c47e323b5ed',
 '9bb74c5c-a641-48cf-b157-1375cd8c7a89',
 '02c626eb-7fb9-46d7-a084-1570db743e0a',
 'f5af8fe6-1fd1-486c-ae19-8bfae75234d6',
 '3a06a14b-e763-43a9-af53-0502f6a771a9',
 '79b08c95-0242-4081-846d-6054e1954148',
 '07b74378-0980-4227-a5af-d408a8f8df10',
 '6cf5f01b-a316-41c2-9bfb-48e73b3a0bbb',
 '581a8984-7372-4dc7-b3e7-e086c230930d',
 'd423ae2d-a551-4816-9baa-4852b58c57ac',
 '2186a4b1-3072-44c4-b8fe-accf91babdcd',
 'd3c9cefc-8f48-4dd2-96a6-d2cd36b82343',
 '7bac3bdb-30f9-48b9-ba24-f024d52c106a',
 'a31ef6ae-fe7e-48d3-a1d3-47323d7b4465',
 'e165d858-f27b-4643-8f6c-9bee40cbe0fe',
 '77eaa385-ddc2-4885-af71-6cc612c874a3',
 'd2667241-147e-4e6b-a5e1-061a21adca03',
 '51ccdcae-caae-4104-bb1f-764c09ddee1f',
 '5ce343d6-99be-4cb3-9e87-e93698f9bfff',
 'e9165a20-4fe2-48df-8235-0def85e72831',
 '4f5e150a-aab1-46bf-ae06-6b3fb2182785',
 'dfc02915-4ffe-4ebb-80dd-32c16f342c5f',
 '09d2be3e-f3c2-4403-bd03-7cd224424fd6',
 '24921d8a-ca66-40b0-a68b-6c4c6bc6c32c',
 '275dfc79-1c0a-4dcc-be89-eb694d4c333e',
 'abf3aade-1a84-4ff2-829e-83ce0508c4d6',
 '6317b37d-d610-46de-bc5d-9f0e2390064d',
 'e36279ce-a81d-4a38-8bef-0a206b48c6b8',
 '8e86bd53-6028-4b04-8ab6-c4b90fe0fe4a',
 '0ab3a30b-f1ea-4052-805e-8b2e878c89f0',
 '3a8b281d-b3d7-48e2-8ba3-fb4c0c333737',
 '9884a53a-1276-461c-a9d6-61ebde1f2e06',
 '81ceeb89-9ae1-4e10-98ad-52c5e12bade8',
 'd4920672-82c2-4d0e-8f8d-91e94054573e',
 'ce693629-e52b-4504-86fb-1c14f4f615fc',
 '442fa118-80ed-4e88-90ed-a6ef49e05680',
 '28cd77a9-c5c1-4ea9-9284-9c47cb06130f',
 '140691a5-b064-4772-93c8-ca347a783e59',
 '3a83d324-54ac-4b3e-a021-4a56236f6622',
 '6115226b-9bc2-4ec2-a3cc-cf7cdeb704b9',
 '2be1a366-8f45-4fd1-bca8-0f102d086f1e',
 'b81a6135-ad75-4e6e-801e-0d3053300465',
 'ccdbd243-4a3a-4dbf-93d9-6dac183644e2',
 'ad461f63-79cd-4339-86f4-d16a556819a2',
 '7c6bf227-0b1e-4a8c-a90d-3eefbfe6e12a',
 '6fcd338c-3be8-4eb9-9f45-ea2920d208cf',
 '68c4ca72-dc80-41ec-9059-b19464a643a8',
 'f113973a-1073-4587-9c50-ea469c15dfe6',
 '0fd1b0a5-45e7-4ca0-817e-93d581f0ae65',
 '66a3f250-b98f-4339-bb1c-fd011120ddaa',
 'd680a05a-d5a0-49ce-902b-83f77f198311',
 'e8346ac6-d5a3-4221-a2db-91bb6b20309f',
 '1bbec20a-aff6-425a-8292-b3105ea7e833',
 '43c8c10d-57ab-423e-ad21-9574c9156c43',
 '40b9dfed-73d0-4d2c-a8e2-bfc978fd230a',
 '38d7eff4-d59c-419d-b75e-de0e56bacd79',
 '5f5d9118-4de6-4d58-a9d7-7cb350285aa5',
 '15202c00-123b-4ee5-b828-4c0b3a2ebdaa',
 '958588bb-120d-40f6-a2dc-4026bb6f2cb6',
 '64d8204f-fc37-45d2-a898-cd4c8208bde0',
 'a86c2332-36bd-4bcb-a77f-464bf8b5d9f3',
 '7d67472c-0161-4851-a24d-86a723f841ac',
 '145c08e0-c72d-4b48-b35a-f58ee545611e',
 'b04be27c-ab43-47d8-b48a-b3f0ae2c8736',
 '3705b39d-4086-482c-ad0f-fb0dde5faa38',
 '83e60a9f-7421-4fba-8732-3cd2fe43477b',
 '0937860b-e851-4850-ae95-943a2758a014',
 '6145a67b-45b4-4e3a-ba6f-0a59ff3db5c0',
 '717e7b70-4074-439a-b281-232510d7a91b',
 '731cb8b6-0a6b-433e-a915-3bc8cb8ca0f3',
 '72b4c5f1-d5cb-478a-88e2-5c10864084f5',
 '95e2713e-6ff9-4990-aad6-b2b371e2c20f',
 '9cdb5f5c-b2cd-442e-a693-5bd91195e194',
 'a50fd63c-1278-4c91-b9ae-0e1f720ec04b',
 '3ed611c0-a5a2-4b00-a344-48f96be22474',
 '334f5eb5-c34b-45c6-83ca-109c46e058e3',
 'f8a36c3d-f191-4734-9ef0-b495cbc84739',
 '5285d6f9-3f9b-4ee7-9975-3035182eb6c4',
 '6ed04a80-09ed-454a-898c-e10865f2a50c',
 '4ced4225-f3ef-4efa-877d-8792d5830f24',
 'dbaece4c-c1ae-489f-af5a-03d6f874d6ed',
 'cefc8364-1a26-4436-b12a-5166907e2e7d',
 'a23c19e8-3078-48d2-b18b-f528d7a37695',
 '973a202f-503f-4b11-bd92-24d876e1a1da',
 '6b413948-79bb-4a8b-965d-d9db511674a1',
 '406df5de-4716-4539-af9f-040fd39c9bdf',
 '99107279-345d-4e1f-9e69-3d7ed46a4905',
 '101f0ec4-b242-4fb6-96cf-6d4ca70b02d8',
 'c3f54f5b-58f2-4d24-a816-43dbb49572e1',
 '5fe411bc-cff1-4703-a9ed-e7b4000dee19',
 'd53b4dfb-e927-4f9f-9860-92870e505edf',
 '495df2bb-d130-468b-b29b-289d57d2b6a1',
 '512301e0-12f6-4421-9bea-10c2d4c85e65',
 '7b9c4222-cb28-4945-85ae-f9f64e3b6ad6',
 'c8a16542-c25b-47c0-9522-29d6c35944d0',
 'c247a297-6f32-4a0c-b4a9-76f875eaaa07',
 'bb57a8e3-9f1d-4882-917e-3fdd722fbd45',
 '9d33f115-08af-4a41-a7c6-07060312534f',
 '36d48efc-5559-4faf-a671-0bd53ca1af38',
 '13f84f2d-3c49-421d-92ca-29444da6e1c9',
 'a4f314e3-6bbd-4408-aa1a-023bb9700a55',
 '821e643b-64b4-4e0f-bed9-d13a9b6f52d9',
 'e31a11ad-2a60-4e52-a858-288cce8881c8',
 'f5cfd6e9-caab-43d7-83d7-0b5115ab94f3',
 '0a892fde-72a4-4a83-9a1c-16569d175d1a',
 'ee47707d-8f82-4e3c-ac04-1f57c24390fd',
 'a71d8e46-9e3f-45a0-ad05-693ba203ca60',
 '82fde8b9-d91d-4a70-9cb5-d6fb2a8e34bf',
 '68417f0b-dacc-4ce6-89d9-3557681de4e7',
 '76cdad28-5f08-4632-a048-a2f72aee73cb',
 '614d09de-c2ac-4611-a260-fbe28616f6f1',
 '39705f3b-d25f-4265-a2aa-c8f9dcacd348',
 'e7d94f43-cab8-49ab-ba08-2fc6cd581a96',
 '3459df33-c57e-4f5a-a9ad-2d77553e9d8c',
 '76c82d9f-2586-4a51-9aa6-12d975236430',
 'a14fd96b-bd9c-46a2-96d5-3face076fd95',
 'be031af8-c3e4-4b3d-ae14-4dae0cdf147f',
 'f478c6ac-580b-4453-a64a-4f51be8b613b',
 'd0527f32-9fe2-4ab6-984c-3e3c8c7f275a',
 '29ffb424-9fdf-410e-ab73-f991e99a24e4',
 'fb04df55-55f2-4591-9930-8222b6c326b5',
 'ce3acf4c-f745-428a-af3f-b6c5e64f63cc',
 '7b795738-e437-4b55-b11f-510643939a27',
 'c20fb5c5-7b00-42d0-b155-d89fb6538b50',
 '417ad2f9-12d8-41e2-91d1-69d88e31f14e',
 '6ce71097-4a8b-4f55-a1c0-171ff4d388da',
 'e566abf1-7f6a-4114-9188-46ded83aa96b',
 '6cf629b1-2836-4c6b-8b06-2366b1221cc0',
 'c401e924-712d-41cc-8739-e4209aab1d3f',
 '957f6398-4f97-49f5-92fa-0fde5808778c',
 'f86b17cb-53f8-42f7-b4dc-8f63f2175ca6',
 'd3231c40-6e0e-485e-8d6c-d3dfd5c9c9da',
 '66181e52-7d3d-4773-80cf-ad2b81168fa7',
 'f07d2fb5-bf68-4828-9def-f09286af23de',
 '0611f0bd-e7fa-4709-b7fc-9d98123f1cec',
 '0f47a990-a1c6-4630-b0a2-9e628dc0039c',
 '73eb5b1e-bd16-4b49-9ccc-810778e9084f',
 '80049c3e-837a-46d6-9b96-c83232e0bde6',
 'f8e0b2f8-5488-45fd-9ce3-0228fae93f0d',
 '86de8a24-a1ae-484e-a199-7a4f902ff533',
 'b053bef2-aca1-4e10-916c-1c543778d588',
 'a80beeca-3d1e-4ae5-b3a6-066f794d40e5',
 '8b6dcd3d-c373-42ff-9456-aef11ebb7e0c',
 'fd96aba1-f5f4-4ca4-80d3-292189fcf784',
 'ea153ba4-48f4-47a9-8214-189071b001ce',
 'caa2a210-3937-4ab8-89af-33407142986c',
 '383f6a4a-c63e-4628-b622-264229d1b197',
 '0aba848b-73e0-47f0-aa76-9820b2f983ee',
 'e960a0bb-8167-49c5-aecf-e20a2c6d60e0',
 'af107b0a-16c0-4ca2-9b6d-dff56f8180ca',
 '8b3d5d70-6d48-4fc6-b945-d0c8c2d647ba',
 'daa0fd9a-e439-4cad-bad9-67a11691128d',
 '0eab8708-2617-4c31-b062-32aa0e92b506',
 '70de2ac5-f862-45b4-bb88-0fade6cd4d3a',
 '174464d0-7f4a-41aa-9706-8af52607c8e5',
 '9325c22f-c1dd-423d-b77b-18c0dd2e3ba0',
 'dd2b5316-ba5e-4cca-811e-e0d027a4d697',
 'ffa2321f-b7eb-4b3d-be59-b563bb27af73',
 '6f3182e6-d479-4895-874e-2c9785d2fae7',
 '55a32073-3aaa-4d24-924d-0ab15177baac',
 '7e995933-d19d-4692-87eb-bc7fa9e60ef4',
 '6275be4e-4161-468b-bf98-936ecf66f33e',
 '93c7dddb-c6b8-436b-b744-1e4a1e32ba23',
 '20a6a002-6df6-49b3-8139-037b72d25fd9',
 '7ebee231-624d-4f5d-9836-80336e57950b',
 '7927659c-1a3d-4380-9ce8-91822db7d085',
 'b7c2a48c-f03d-4b17-ad21-0847cf0513d3',
 'c428c766-731d-44f7-b956-aeca51e4693f',
 '03febb23-eace-4f75-bfe7-17d19299ffbb',
 '2a3ff1ec-cdb6-4203-8d99-c71bbd973700',
 'c834da73-e4ed-4751-b036-b91c12c5b3cd',
 '8f0dd03f-76fe-41ae-b704-15312602949d',
 'b5d1fa10-d193-4686-9823-bb1707286c04',
 '54f66688-5f53-461c-85f7-43a54c18eb46',
 '8b365674-63ca-404a-b26e-7b2b2192e4b9',
 'a9393282-8f5d-4e3d-bce2-6bc63deb2ec2',
 'f6019921-565e-410f-aaf2-85a5d0699055',
 'cf633b4b-c241-4273-9b44-7cb4e75b1d30',
 'e3c8e9af-f916-4d06-865e-064d026993a8',
 'bc820760-e232-423a-8812-e40c26f10e69',
 '103ba037-f8a4-4067-a6ba-a2b9da8b5f2f',
 '6dc5f869-b01d-4384-9ecd-cbe4ae457b03',
 'ef97bd53-5a62-4f1c-b4b8-6327f65a2dbe',
 'be6afd54-5b26-49bd-bf08-1b7f1fc5c80d',
 '67ee2bf1-487c-4feb-afc5-2ea7213b2766',
 'f2e3859e-8fc2-455e-b13d-74613b6d1ddf',
 '1bc03e30-5338-4e6a-a064-84aa6433fb62',
 '2769def2-b19e-46d4-b1c1-003554bdc6da',
 '3355b871-f59c-4124-954c-56f7a91f6f17',
 '139641e7-8f32-4382-b0ae-bd007ba90493',
 '2885f8cc-3dd8-4358-9170-e5d7b11c0174',
 'fb0fa784-0cb0-4630-a125-0278d5eb90bf',
 '5b9c17c5-ce8f-4b83-8c5a-7763ebad8533',
 '184a3113-bbb9-4174-b84b-f7ab9db0108f',
 'dde9e535-8ff5-495f-968c-14a0debe2034',
 'ee868d9f-3c97-49ec-9581-0f09465d8786',
 '74c3fbb8-452c-4054-806d-de4892b9583f',
 '71623421-e61b-4b37-88d7-dcd7b202b067',
 'c949f274-b3ae-4782-8ff5-598c742eb6ac',
 '00cc1e03-b2df-4e9d-bfa5-6a1c9d9c901b',
 '764f839d-e7db-4376-885b-3facb4c23a8e',
 '625938cf-f908-4f58-81aa-c62c12854da8',
 '0bd93863-9990-46a2-8d8e-400b835fabd5',
 'b03aa00c-9fff-4dd2-9a7d-03f8becc91d3',
 '75843bf6-c81c-47b8-afda-c29d65d70dc8',
 '57f415d4-3166-4f15-9d09-e36b294f9171',
 '6b4f31f2-abc7-411c-97ee-1af779fe7f65',
 '61a854ff-94b7-4e95-837e-cabb9b468ad3',
 'd7a6cf9c-7c17-416b-b1a6-3f508a0ad3df',
 'bdd32c70-e720-4f3f-9226-e87d7fd2008c',
 'ad81f4f0-ec3c-49da-b10f-96088ee485e0',
 'fc20e029-2c9a-46b5-afcf-f7c6025a1cd9',
 '87c703cf-caaa-490c-b17c-c500cfee467a',
 '3dd8050c-b15c-4fe3-bf57-f1eb4c0d654e',
 '982aac79-2bc0-453d-8d1c-335c0bde3a67',
 '6dcf2db7-e458-449e-a2c1-5a0412f11997',
 '638881fc-a328-4ac6-b27b-42e01232becf',
 '8e26e02e-c526-4309-80f8-4c5b248040aa',
 'fd223db8-4aed-4cb9-85ab-9fa8cd855100',
 '2cc67d1a-08ac-4a38-8b32-6cd7b1b79242',
 'c02c64dc-5e52-449b-9985-929b33a5c31f',
 '5295ffdb-229d-4a10-a78f-ee3a1c8adf55',
 '91a73f4c-73a6-4837-9d50-54082a1cea73',
 '14e6240f-833f-4e37-a996-680071e6d4a0',
 'd2e59f1f-4e64-4d14-8da2-98298cca85c1',
 'fa1f6a93-a6d5-42df-b074-347ff14b4a78',
 '33daef87-9548-458c-8c6a-21bdeddb3d6f',
 '02d3ab86-06b3-4de7-b33b-7c766e385074',
 'b822589a-07ff-4195-844d-0d9dcf7fcba6',
 'd3d23705-211c-4d2e-a0f7-5848d32d9512',
 '2705b93a-1914-4a4a-a1de-dc754313479d',
 '7c546fa4-f8d1-46fb-8c15-aae7cf8c6c86',
 'be9cbbb1-45a3-4d97-947f-df0fba72d17a',
 '1811cf82-4a61-410b-9a1b-3588d2dd722a',
 '87cb7427-b9a6-4bbe-81a3-a9f1047dcc2e',
 'd58f6ef5-6127-4f0f-bcf4-e233d606466d',
 '9f88ff21-4f57-4500-bf07-c3f0142e9a92',
 'd2cd08b4-6743-48c4-9b2c-ee2d222459ef',
 '67956880-9104-4c9d-aeb4-86adf2718c2e',
 'c47f0e71-1440-49a5-9651-5825a75e1175',
 '3728e905-f6e1-4ed2-ac45-6a4e5622012e',
 '5b0601f0-28d4-4a66-adef-587a697a5b14',
 'a157b4d3-9562-4335-bef8-8567b442b7c4',
 '2e183753-39b8-4ea7-bcf3-5a8350ba1dee',
 '81a65ba3-a6ce-4e0b-9c33-7eee26402692',
 '07df4222-113b-4cda-b732-cb5757754b83',
 'b11180f2-b34e-4550-ad7e-1c6b9c3d4ecc',
 'e027641d-9c35-4dba-b5a5-9e45e8568fb5',
 '2d635f6f-37ee-43f5-8a0b-b794480cbacd',
 '957d87b6-c831-487d-83e8-87917cc311e8',
 '6c5390cf-36cc-430b-bb92-1438a3d1c139',
 'cbb9f947-018f-4d5d-bb53-ab0899e5d719',
 '15391cce-da0c-4e90-b655-036213b6e7c3',
 'aa4cdd70-87cf-4011-b0b2-29864832f111',
 'ea7f13de-717a-4901-af44-459b60c1b4c0',
 'c3783439-aebb-42d5-b8da-a87cfcafcf0e',
 '1a2bcea3-9160-4d39-a854-8e4e51e6277f',
 'ce3c0b02-d63f-4be5-9962-22b781539175',
 '200cc79d-11aa-44c2-81de-5b6cff0b8019',
 '8f72d4c2-a350-4c0a-a208-7f3e13014fe4',
 'ed6008f0-7ad2-4d78-836e-92f6b9ac3e74',
 '1c95c0d4-4bc8-4a3a-9345-772c7211a036',
 'ed3cf419-4935-4ad7-ac66-40e520b3680b',
 '7cb21215-0122-4926-a222-7cd01b1bc40b',
 'ca5444d0-b1bc-4927-8ee8-46b66d72acf8',
 'c016c66c-eda1-4c72-8c65-8ad7e827e661',
 '2d1cbdca-ecaa-4f15-88c7-cf8bf1d7f054',
 'e247cb68-37a2-4aab-a4c3-f587de55f069',
 'e8b59184-55c8-4451-a734-fa8388116821',
 '0b3d5446-dba4-4ed5-8665-083c5b5bca8e',
 '70bab11f-5b4b-49f6-812c-f22f1e704014',
 '2921f22b-a944-46b4-8509-d6642a37013e',
 '7543ab26-6e51-473b-9291-f29ccf30fcb2',
 '52a0f9cc-d467-4777-bcdd-800bfbd12ffb',
 '0652af79-c35a-45ef-886a-df11fab31d55',
 'd6158177-b1cb-434e-b159-69c603558980',
 '827f4c1f-57e4-402a-816d-44ec689cbc5d',
 '4ce6eb56-0923-4927-8d1e-b3ab77eb3ad9',
 '59ac6b8e-8794-4378-bfb9-ed881ecae843',
 '4cea9c1b-d020-4619-97b5-af28ce9e2ca4',
 'a85fd0c3-aa60-460e-b460-798f69f7f884',
 '771f28a6-0189-42cd-9b84-7078bf9f40dc',
 '77d2ed09-b558-472f-8b99-cdec224317e7',
 'b1df912f-94c2-4f12-b1df-4a6d526049ec',
 'ab9b7f29-5aed-40a2-b703-5e788d0bde11',
 '1a0ccf54-6b83-4b93-acd0-e159947963cb',
 'dbb22ec9-10c8-49fc-b37e-3e2bd3e989c5',
 '93a66991-7e5d-44e9-afb4-58077aa0644f',
 '553793cf-48e4-4c3f-a4d2-14d7c0552786',
 '28d9a2d8-6290-47cf-9dc8-e00ab252ad61',
 '123c6c69-0a53-4484-a180-9ec03035c377',
 '64a0ac29-9629-4f40-8693-83a8f7757171',
 'adcaaa77-e3f9-4511-9b4f-66ef6a8dacda',
 '4514a9a1-a9e6-4601-85c4-75118d22b16c',
 'b22b0fff-11f6-4952-a233-71908513c194',
 '271bd9ce-09e9-44ff-a6be-12b503414ff5',
 'f825c6c8-e66f-4ef0-8514-8b2d75165a5a',
 '32d3d424-8a02-44fe-acee-3d8059cc35e2',
 '7a6d5335-1c56-4ccc-adea-67a810daff91',
 '41735c00-7dce-47ca-b7d2-2d43aff23786',
 'fe2a25d6-d3af-4223-ae9c-a6a315c2f37f',
 '0034169c-596a-4b5b-96b2-864030ea747f',
 'f3368ee0-d471-44d3-aae0-c5bb5ce6ac4d',
 '462de2b1-35a6-4a4b-925f-80ea4e998f0e',
 '112e573b-87e1-4fb2-9428-a73a725f9f1a',
 'f7fbe6ee-6d58-4fe1-966f-ba3ef93fa6e9',
 '73f67f9b-1c78-4917-91b3-afbad6261d84',
 'cc49ab78-8ffb-4201-9103-196db2f4d9d7',
 'ef73d915-85c4-404a-948a-ccc12edb376a',
 'e2bd38cb-46a2-419a-9eb1-796ab18e37b2',
 'e16a846e-7eed-4b90-8d23-5563bbff2dd6',
 'ed7b388c-f127-466f-a817-2d5d8384b41f',
 '6394d4aa-0e87-440f-882a-c967dc6690d2',
 '5f4d750b-5478-4f0d-b118-f527ae6ffed8',
 '2adb2c32-3979-4897-8b37-1b275307871e',
 '40275072-126c-460f-b72d-a3b934320989',
 'f4847a41-4124-49cd-9a45-ad358ca99435',
 '7f16a854-ef6a-4191-97e6-2d35e32d9a8b',
 '5af5e28f-e800-4eb7-b511-abae39800dbd',
 '2bee8fc2-a645-4b46-8b95-52d1e453e1f9',
 '0a33cbcc-2de2-455c-8b2e-10b8a7340762',
 'e97b1cd8-db9f-4f4f-99db-bf14ecbd84d3',
 '8d38ce0e-d9eb-4dae-837d-badc12400264',
 '7cb8b3eb-50ad-43bb-b1ae-4959519526fb',
 'ace6fb37-8ffc-4191-a285-9de1563b5826',
 '8b042c12-d689-4c5c-98b0-24b0b8622c4f',
 '78eeff98-92d1-4284-b2ea-2eeb06c04e11',
 'b0731ccf-834f-4a22-b93e-1ab3afd967cd',
 'e742f772-7701-4ba8-b524-79377d1561e5',
 '38b98902-0e3e-47b2-8ceb-8ab1cbc48935',
 'de37bfcf-9f7f-4427-b83c-1c2f9a8a4dd0',
 '752fa874-2f55-4730-8d14-c8c2bfb48b31',
 '4f5fb6c0-1070-4486-b7f7-fb3d13063498',
 '2e82894d-6bde-4752-b361-11cc2f3475d8',
 '999b5b5a-f09f-4b2a-9f65-fc496638893b',
 'acb86378-8364-492c-8281-13272109b09f',
 'ebdc7573-8f08-4a99-bdfb-199113e9f384',
 '60f23979-83be-41f5-b273-64b170dc1cab',
 '59de2732-4fa3-47ac-bb40-3485b9a9658f',
 'b1ac81db-dc42-4123-90c2-1ee603986fa0',
 '18a094c4-7a02-469a-b6a1-eedc0d9984d5',

In [113]:
GOOGLE_KEYS = []

for i in range(10):
    possible_name = f"GOOGLE_API_KEY_{i + 1}"
    if os.getenv(possible_name):
        GOOGLE_KEYS.append(os.getenv(possible_name))

key_index = 0
def get_next_google_key():
    global key_index
    key = GOOGLE_KEYS[key_index]
    key_index = (key_index + 1) % len(GOOGLE_KEYS)
    return key

In [90]:
system_prompt = """
You are a helpful reasearch assistant. Your task is to help the user with their research and do the requested tasks no matter how difficult they are.
You should always try to use the rag tools to check if the answer can be found in the database of text passages. Try very hard to find the answer in the database.
You are given access to a database of text passages and a RAG system that can help you access the information about the selected passages.
When you are asked a question, you should first check if the answer is in the database.
If the question is not related to the passages, inform the user that the question is not related to the passages (it will happen rarely) and you cannot help them with that (BUT ONLY AFTER YOU HAVE CHECKED IT USING THE TOOLS!).
If you are unsure whether it is related to the passages, you should assume that it IS. You MUST always assume at first that the question is related to the passages and check it using the tools.
You should use tools rather too much than too little. You should try your best to answer the question using the tools.
You can use the tools as many times as you want, prioritirize using elastic_search_tool over rag_tool, but if you cannot find the answer using elastic_search_tool, you should use rag_tool.
REMEMBER: the passages are about a lot of different topics, so you should not assume that the question is not related to the passages just because it is about a specific topic.
"""

prompt = ChatPromptTemplate.from_messages(
    [
        ("system", system_prompt),
        ("human", "{input}"),
        ("placeholder", "{agent_scratchpad}"),
    ]
)

In [ ]:
def answer_question(question: str) -> tuple[str, list[str]]:
    os.environ["GOOGLE_API_KEY"] = get_next_google_key()

    llm = ChatGoogleGenerativeAI(
        model="gemini-2.5-flash-preview-04-17",
        temperature=0,
        max_tokens=None,
        timeout=None,
        max_retries=1,
    )

    rag_chain = RetrievalQA.from_chain_type(
        llm=llm,
        chain_type="stuff",
        retriever=dataset_vector_store.as_retriever(search_kwargs={"k": 3}),
    )

    retrieved_context = []

    @tool
    def rag_tool(query: str) -> str:
        """Use this tool to get information from the RAG model if needed.
        This tool allows you to ask questions about the papers selected by the user.
        This tool should return the answer with all the necessary citations.
        Sometimes the tool will not be able to answer the question, in that case, you should try to formulate the question in a different way.
        Most often than not, the problem with this tool's answer will be in your question formulation, so you should try to rephrase it them
        as this tool will try to answer your question very literally.
        """
        output = rag_chain.invoke(query)
        retrieved_context.append(output['result'])
        return output

    @tool
    def elastic_search_tool(query: str) -> str:
        """Use this tool to get information from the Elasticsearch index if needed.
        This tool allows you to ask questions about the papers selected by the user.
        This tool should return the answer together with the metadata of the paper, by default returning the first 3 results.
        """
        results = dataset_vector_store.similarity_search(query, k=3)

        response = ""
        for i, result in enumerate(results):
            response += f"Result {i+1}:\n"
            response += f"ID: {result.metadata['id']}\n" if "id" in result.metadata else "N/A\n"
            # response += f"Title: {result.metadata['title']}\n" if "title" in result.metadata else "N/A"
            # response += f"Authors: {result.metadata['authors']}\n" if "authors" in result.metadata else "N/A"
            # response += f"DOI: {result.metadata['doi']}\n" if "doi" in result.metadata else "N/A"
            # response += f"Page: {result.metadata['page']}\n\n" if "page" in result.metadata else "N/A\n\n"
            response += f"Content:\n{result.page_content}\n\n\n\n"

        retrieved_context.append(response)
        return response

    tools = [rag_tool, elastic_search_tool]

    agent = create_tool_calling_agent(llm, tools, prompt)
    agent_executor = AgentExecutor(
        agent=agent, tools=tools, verbose=True, max_iterations=15
    )
    output = agent_executor.invoke({"input": question})[
        "output"
    ]

    print(f"Question: {question}")
    print(f"Answer: {output}")

    return output, retrieved_context

In [88]:
def build_evaluation_dataset(queries, references, retriever, formatter):
    data = []
    for query, reference in zip(queries, references):
        response, relevant_docs = answer_question(query)
        data.append({
            "user_input": query,
            "retrieved_contexts": relevant_docs, # [f"Document id {doc.metadata["id"]}:\n{doc.page_content}" for doc in relevant_docs],
            "response": response,
            "reference": reference,
        })
    return EvaluationDataset.from_list(data)


def format_docs(relevant_docs):
    return [f"Document:\n{doc.page_content}\n\n" for doc in relevant_docs]

In [ ]:
evaluation_dataset = build_evaluation_dataset(
    list(train_df['query']),
    list(train_df['answers']),
    dataset_vector_store,
    format_docs
)

> Entering new AgentExecutor chain...

Invoking: `elastic_search_tool` with `{'query': 'why did we declare war on germany?'}`


Result 1:
ID: 0034_0
Content:
Why did the U.S. declare war on Germany during WW2? World War II: After the U.S. declared war on Japan following their surprise attack on Pearl Harbor, it was clear that the U.S. could not stay out of World War II as a neutral party. However, despite the alliance Japan had with Germany and the U.S. had with Britain, it was not clear that the U.S. had a national interest in war with Germany nor that Germany had one with the U.S. Why did the U.S. declare war on Germany?



Result 2:
ID: 0034_1
Content:
Why did Britain and France declare war on Germany in September 1939? Britain and France declared war on Germany following the invasion of Poland two days before. This was due to many factors, including the famous Nazi-Soviet Pact; where Russia and Germany split Poland in half, resultantly giving Germany the confidence to invade Poland. '



Result 3:
ID: 0031_1
Content:
The United States declared war on Germany for many reasons. One of them was the sinking on neutral ships and the lusitania which killed about 148 Americans. This was not the immediate cause, another is propaganda which persuaded public opinion.



Based on the information from the passages, there are several reasons and instances mentioned for declaring war on Germany:

*   **United States in WW2:** After the attack on Pearl Harbor and declaring war on Japan, the U.S. could not remain neutral. While not immediately clear that the U.S. had a national interest in war with Germany, war was declared.
*   **Britain and France in September 1939:** These countries declared war on Germany following the invasion of Poland. Factors contributing to this included the Nazi-Soviet Pact, which led to Germany invading Poland.
*   **United States (other reasons):** The United States also declared war on Germany for reasons including the sinking of neutral ships like the Lusitania, which resulted in American deaths, and the influence of propaganda on public opinion.

> Finished chain.
Question: why did we declare war on germany?
Answer: Based on the information from the passages, there are several reasons and instances mentioned for declaring war on Germany:

*   **United States in WW2:** After the attack on Pearl Harbor and declaring war on Japan, the U.S. could not remain neutral. While not immediately clear that the U.S. had a national interest in war with Germany, war was declared.
*   **Britain and France in September 1939:** These countries declared war on Germany following the invasion of Poland. Factors contributing to this included the Nazi-Soviet Pact, which led to Germany invading Poland.
*   **United States (other reasons):** The United States also declared war on Germany for reasons including the sinking of neutral ships like the Lusitania, which resulted in American deaths, and the influence of propaganda on public opinion.

In [110]:
datetime_str = datetime.datetime.now().strftime("%Y_%m_%d_%H_%M_%S")

with open(f"evaluation_dataset_{datetime_str}.pickle", "wb") as f:
    pickle.dump(evaluation_dataset, f)

In [ ]:
llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash-preview-04-17",
    temperature=0,
    max_tokens=None,
    timeout=None,
    max_retries=1,
)

In [99]:
run_config = RunConfig(timeout=60*10, max_workers=1)
evaluator_llm = LangchainLLMWrapper(llm)

In [100]:
result_correctness: EvaluationResult = evaluate(
    dataset=evaluation_dataset,
    metrics=[FactualCorrectness()],
    llm=evaluator_llm,
    run_config=run_config,
)

result_correctness

Evaluating: 100%|██████████| 1/1 [00:23<00:00, 23.89s/it]

{'factual_correctness(mode=f1)': 0.4000}